Added lint to Earthfile
expect-digital/translate pull request #10
Opened 2022-12-23 12:01 UTC by VladislavsPerkanuks

2022-12-23 12:02 UTC, VladislavsPerkanuks commented on Earthfile
> +  RUN apk add build-base
Needed for golancgi-lint else error is thrown
https://github.com/golangci/golangci-lint/issues/3289

2022-12-23 12:06 UTC, VladislavsPerkanuks commented on Earthfile
> +  RUN go mod download
Don't like this, as firstly: redownloads every time, if something is changes as we don't save the artifact, secondly: not really the thing that target should be doing.
My suggestion, another target that generates those files, go mod init, etc. and then saves as local artifact

2022-12-23 14:04 UTC, janishorsts requested changes

2022-12-23 14:04 UTC, janishorsts commented on .golangci.yml
> +    - pkg/server
Let's add the following lint rules

```yaml
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wrapcheck
    - wsl
linters-settings:
  govet:
    enable-all: true
```

2022-12-23 14:04 UTC, janishorsts commented on Earthfile
> +  RUN apk add build-base
We are not gonna use cgo, you can disable it with `ENV CGO_ENABLED=0` or `RUN go env -w CGO_ENABLED=0`.

2022-12-23 14:04 UTC, janishorsts commented on Earthfile
> +  RUN apk add build-base
```suggestion
  ENV CGO_ENABLED=0
```

2022-12-23 14:04 UTC, janishorsts commented on Earthfile
> +  RUN go mod download
There are a few options with `earthly` to optimize it, the simplest one - you can create a target from another target (continue flow).

```earthly
deps:
  COPY go.mod go.sum .
  RUN go mod download
  SAVE ARTIFACT go.mod AS LOCAL go.mod
  SAVE ARTIFACT go.sum AS LOCAL go.sum
  
lint-go:
   FROM +deps
   RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v$golangci_lint_version
   COPY --dir pkg .
   COPY .golangci.yaml .
   RUN golangci-lint run
```

2022-12-23 14:04 UTC, janishorsts commented on Earthfile
> +ARG go_version=1.19.4
Be consistent in value assignment - in one place you don't have an assignment operator, in another you do.

```earthly
ARG go_version=1.19.4
// vs
ARG go_version 1.19.4
```

2022-12-27 09:56 UTC, janishorsts approved these changes

2022-12-27 10:20 UTC, merged