22 upload translation file
expect-digital/translate pull request #24
Opened 2023-01-02 10:42 UTC by VladislavsPerkanuks

2023-01-02 10:48 UTC, VladislavsPerkanuks commented on .vscode/extensions.json
> +  "recommendations": [
https://dev.to/askrishnapravin/recommend-vs-code-extensions-to-your-future-teammates-4gkb

2023-01-02 11:00 UTC, VladislavsPerkanuks commented
As I understood, clients will have to encode the data to bytes themselves, e.g. when requesting using curl
```bash
curl --location --request POST 'localhost:8080/v1/upload/translationfile' \
--header 'Content-Type: application/json' \
--data-raw '{
"data" : "ewoiYSI6ImIiLAoiYS5jIiA6ICJkIiwKInZsYWRpc2xhdnMiOiJwZXJrYW5rcyIKfQ=="
}'
```

2023-01-02 14:47 UTC, DarjaLeonova approved these changes

2023-01-03 15:59 UTC, VladislavsPerkanuks commented on api/translate/translate/v1/translate.proto
> +      body: "*"
Example curl
```bash
curl --location --request PUT 'localhost:8080/v1/translations/asd' \
--header 'Content-Type: application/json' \
--data-raw '{
    "labels": {
        "aaa": "bbb",
        "version": "!"
    },
    "type": "NGX_TRANSLATE",
    "data": "{\"vlad\":\"perk\",\"beep\":{\"hey\":\"world\"}}"
}'
```

2023-01-03 16:00 UTC, VladislavsPerkanuks commented on pkg/convert/go.go
> +func FromGo(b []byte) (model.Messages, error) {
Refactored so it's consistent with other converts

From: bytes→messages
To: messages→bytes

2023-01-03 16:09 UTC, VladislavsPerkanuks commented on pkg/translate/translate.go
> +	case pb.Type_TYPE_UNSPECIFIED:
Not good-looking, but it's required by buf-lint to pass. It requires for enum in.proto files to be prefixed with "TYPE_"

2023-01-04 11:30 UTC, VladislavsPerkanuks commented on api/translate/translate/v1/translate.proto
> +      body: "data"
Example curl:
```bash
curl --location -g --request PUT 'localhost:8080/v1/translations/asd?type=NGX_TRANSLATE&labels[version]=1&labels[date]=2023-01-04' \
--header 'Content-Type: application/json' \
--data-raw '"{\"vlad\":\"perk\",\"beep\":{\"hey\":\"world\"}}"
'
```

2023-01-04 19:08 UTC, janishorsts requested changes

2023-01-04 19:08 UTC, janishorsts commented on .vscode/extensions.json
> +  ]
```suggestion
  "recommendations": [
    "bufbuild.vscode-buf",
    "earthly.earthfile-syntax-highlighting",
    "emeraldwalk.runonsave",
    "mikestead.dotenv"
  ]
```

2023-01-04 19:08 UTC, janishorsts commented on pkg/translate/translate.go
> +	}
Functions are first-class citizens in golang. Define `type From = func ([]byte) (model.Messages, error)` in the `convert` package.

```suggestion

	var from convert.From
	
	switch v := req.GetType(); v {
	default:
		return nil, status.Errorf(codes.Unimplemented, "Type '%s' is unimplemented", pb.Type_name[v])
	case pb.Type_TYPE_UNSPECIFIED:
		return nil, status.Errorf(codes.InvalidArgument, "Type is missing")
	case pb.Type_NG_LOCALISE:
		from = convert.FromNgJson
	case pb.Type_NGX_TRANSLATE:
		from = convert.FromNgxTranslate
	case pb.Type_GO:
		from = convert.FromGo
	}
	
	messages, err := from([]byte(req.Data)
	// ...
```

2023-01-04 19:08 UTC, janishorsts commented on pkg/translate/translate.go
> +		return nil, fmt.Errorf("convert to messages: %w", err)
```suggestion
		return nil, status.Errorf(codes.InvalidArgument, "parse data: %w", err)
```

2023-01-04 19:08 UTC, janishorsts commented on pkg/translate/translate.go
> +	_ = messages
```suggestion
	messages.Labels = req.GetLabels()
	_ = messages
```

2023-01-05 09:00 UTC, VladislavsPerkanuks commented on pkg/translate/translate.go
> +	)
Moved all request variables to one place, I think it's tidier that way + getters are called only once per variable

2023-01-05 09:02 UTC, VladislavsPerkanuks commented on pkg/translate/translate.go
> +	}
Deleted `default` as it is impossible to get in that case. Neither gRPC request allows calling with unsupported type, nor REST.

2023-01-05 10:25 UTC, janishorsts requested changes

2023-01-05 10:25 UTC, janishorsts commented on pkg/convert/go.go
> +type From = func([]byte) (model.Messages, error)
It applies to all `func convert.From<name>()`. Why in `go.go`? Why not `convert.go` to emphasize its context of use?

2023-01-05 10:53 UTC, VladislavsPerkanuks commented on pkg/convert/go.go
> +type From = func([]byte) (model.Messages, error)
Over sighted

2023-01-05 11:17 UTC, janishorsts approved these changes

2023-01-05 11:20 UTC, merged