#23 Download translation file initial implementation
expect-digital/translate pull request #25
Opened 2023-01-02 14:59 UTC by VladislavsPerkanuks

2023-01-04 11:38 UTC, VladislavsPerkanuks commented on api/translate/translate/v1/translate.proto
> +    option (google.api.http) = {get: "/v1/translations/{translation_id}"};
Example cURL:
```bash
curl --location --request GET 'localhost:8080/v1/translations/asd?type=TYPE_NGX_TRANSLATE'
```

2023-01-04 19:14 UTC, janishorsts commented on pkg/translate/translate.go
> +	var (
The same way I advised [here](https://github.com/expect-digital/translate/pull/24/files#r1061771670)

2023-01-05 10:26 UTC, janishorsts requested changes

2023-01-05 10:26 UTC, janishorsts commented on pkg/convert/go.go
> +type To func(model.Messages) ([]byte, error)
`convert.go`?

2023-01-05 11:16 UTC, janishorsts approved these changes

2023-01-05 11:16 UTC, janishorsts approved these changes

2023-01-05 11:58 UTC, merged